# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 630b26fc39c60a828ac2f2c27985c3e1a1d00cd8c62417bab36ac7f07d1bbd02954de163439aa614f606075a04d488051d04dbaa689f7c8c1c45f968382d940f

test:
  secret_key_base: 1ca69eb576311b5e407c7b3bb0a7aa07f7622617a24d4b1e8d07918956ca799bc19c3634538b8b181fb479ea49a8c929313905f0155ccc9d0e91d6969eb05453

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
